### PR TITLE
fixed comments starting with '#'

### PR DESCRIPTION
**Pull request by acidghost**
Hello there!

This PR enables syntax highlighting for comment lines starting with '#' (without breaking preprocessor commands highlighting).

### CODE REVIEW

**Comment by 13xforever** [comment]
I do not accept PRs on [exported projects](/13xforever/language-x86_64-assembly#source-code) as it's meaningless and will be lost after next export.

I will write it down for the next update though.

**Comment by acidghost** [comment]
Would it be useful a PR on that repo changing [this](https://github.com/13xforever/x86-assembly-textmate-bundle/blob/master/x86_64%20Assembly.tmbundle/Syntaxes/x86_64%20Assembly.tmLanguage) file to enable comments starting with an hashtag?

**Comment by 13xforever** [comment]
[Sources](/13xforever/x86-assembly-textmate-bundle/blob/master/x86_64%20Assembly.tmbundle/Syntaxes/x86_64%20Assembly.YAML-tmLanguage) are in yaml, so you can do PR on it. I'll still have to update everything and push new versions though.

**Comment by acidghost** [comment]
So shall I wait for a ping from you before creating a PR?

**Comment by 13xforever** [comment]
No, go ahead. I can't say how fast I'll be able to push it out though, as I kinda have a problem with free time right now.

**Pull request closed without merging**
